FROM qmcgaw/latexdevcontainer:latest-full

RUN apt update -y && apt install fontconfig python3 python-is-python3 python3-pip -y
RUN python -m pip install ipython matplotlib numpy pandas Pillow scipy torch torchaudio torchvision